source .env

flyctl secrets set ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" --config fly.api.toml \
    COMFYUI_API_URL="$COMFYUI_API_URL" \
    DISCORD_API_TOKEN="$DISCORD_API_TOKEN" \
    DISCORD_GUILD_IDS="$DISCORD_GUILD_IDS" \
    GOOGLE_SEARCH_API_KEY="$GOOGLE_SEARCH_API_KEY" \
    GOOGLE_SEARCH_ENGINE_ID="$GOOGLE_SEARCH_ENGINE_ID" \
    COMFYUI_API_URL="$COMFYUI_API_URL" \
    HUGGINGFACE_TOKEN="$HUGGINGFACE_TOKEN" \
    OPENAI_API_KEY="$OPENAI_API_KEY" \
    YOUTUBE_API_KEY="$YOUTUBE_API_KEY" \
    NEWSAPI_KEY="$NEWSAPI_KEY" \
    FAL_KEY="$FAL_KEY"

source .env

flyctl secrets set ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
    COMFYUI_API_URL="$COMFYUI_API_URL" \
    DISCORD_API_TOKEN="$DISCORD_API_TOKEN" \
    DISCORD_GUILD_IDS="$DISCORD_GUILD_IDS" \
    GOOGLE_SEARCH_API_KEY="$GOOGLE_SEARCH_API_KEY" \
    GOOGLE_SEARCH_ENGINE_ID="$GOOGLE_SEARCH_ENGINE_ID" \
    COMFYUI_API_URL="$COMFYUI_API_URL" \
    HUGGINGFACE_TOKEN="$HUGGINGFACE_TOKEN" \
    OPENAI_API_KEY="$OPENAI_API_KEY" \
    YOUTUBE_API_KEY="$YOUTUBE_API_KEY" \
    NEWSAPI_KEY="$NEWSAPI_KEY" \
    FAL_KEY="$FAL_KEY"