source .env

/Users/claym/.fly/bin/flyctl secrets set DISCORD_API_TOKEN="$DISCORD_API_TOKEN" DISCORD_GUILD_IDS="$DISCORD_GUILD_IDS" ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" OPENAI_API_KEY="$OPENAI_API_KEY"
  YOUTUBE_API_KEY="$YOUTUBE_API_KEY" GOOGLE_SEARCH_API_KEY="$GOOGLE_SEARCH_API_KEY" GOOGLE_SEARCH_ENGINE_ID="$GOOGLE_SEARCH_ENGINE_ID" COMFYUI_API_URL="$COMFYUI_API_URL"
